### ISSUE TITLE
Reflection in GHG-EMIT Plume data 

### ISSUE THREAD

**Issue by siddharth0248** [NASA-IMPACT/veda-ui#600]
Some of the COGs have weird reflections displayed on the dashboard.

![image](https://github.com/NASA-IMPACT/veda-ui/assets/118487103/e09213b2-4ae0-46fe-bfa9-5caec7ef4a23)

**Comment by siddharth0248** [comment]
@aboydnw please look into this bug

**Comment by aboydnw** [comment]
Thanks @siddharth0248 
@danielfdsilva reproduction steps for the team:
1. Open GHG center dashboard
2. Go to EMIT Methane Emissions Plume dataset
3. Click to Explore Data
4. Change date to August 14th to see an example, although other dates have a similar issue
5. After the map zooms in, zoom out slightly and you will notice a shadow that was originally just outside the border of the screen

@siddharth0248 let me know if I got any of those steps incorrect, I tried to work backwards from your screenshot

**Comment by danielfdsilva** [comment]
This is very strange. Looking at the tile requests there doesn't seem to be anything wrong - the tiles that come in look clean.
However I don't see this happening with any other dataset. Could there be something weird going on with the tiler response? Tiles too small, misconfigured values? (just throwing things out here, not sure if they make sense) cc @smohiudd @vincentsarago

**Comment by danielfdsilva** [comment]
I don't know if this is useful at all, but in the example given the shadow is caused by the rendering of this tile:

https://2qncpyg24c.execute-api.us-west-2.amazonaws.com/api/raster/mosaic/tiles/0717b7cadd852b7131c309717ea06910/WebMercatorQuad/8/157/101@1x?assets=ch4-plume-emissions&resampling=bilinear&bidx=1&colormap_name=plasma&rescale=1%2C1500&nodata=-9999

If I block this specific url, then the shadow does not appear in this case. Not sure why this happens, given that the tile looks clean. 🤔

**Comment by smohiudd** [comment]
This one is very strange. @danielfdsilva, can confirm that I can reproduce the issue with the same tile you have linked above. I checked the underlying COG and confirmed it's valid. I even recreated it just in case and still getting the same issue. I also rendered this with `rio-viz` (which doesn't use mapbox) and I'm **not** getting the shadow. 

I'm only seeing this issue on 2022-08-14 and 2023-05-04 so far.

**Comment by smohiudd** [comment]
This may be an issue with the tile resampling. I tried `nearest` and one of the problem area is fixes (2022-08-14):

![image](https://github.com/NASA-IMPACT/veda-ui/assets/34844565/972a82aa-3513-48f0-903f-e5d8c6ec2ac6)

However still have an issue with 2023-05-04:

![image](https://github.com/NASA-IMPACT/veda-ui/assets/34844565/cd782c4d-c4d4-42b9-aaf9-11e26a6fd510)

**Comment by danielfdsilva** [comment]
this is so strange...

**Comment by smohiudd** [comment]
Maybe it was a caching issue but looks like 05-04 is fixed now: 

![image](https://github.com/NASA-IMPACT/veda-ui/assets/34844565/86a0bcee-907f-4342-bb12-e2a73597ebf1)

Can someone else do search and see if they can find any more problem tiles? I can't seems to find anymore:

https://github.com/NASA-IMPACT/veda-config-ghg/pull/54

https://deploy-preview-54--ghg-demo.netlify.app/

**Comment by j08lue** [comment]
Nope, issue persists, at least for me: https://deploy-preview-54--ghg-demo.netlify.app/data-catalog/jpl-ch4-plume-emissions/explore?datetime=2023-05-04T00%3A00%3A00.000Z&position=-46.4651%7C-23.5963%7C10.95

![image](https://github.com/NASA-IMPACT/veda-ui/assets/3404817/3ac53f44-e273-4f55-b704-f3fe9bedfecb)

In this case it is this tile:

https://2qncpyg24c.execute-api.us-west-2.amazonaws.com/api/raster/mosaic/tiles/82e82d2c69aa16fdaa88d5cf0f157c74/WebMercatorQuad/7/47/72@1x?assets=ch4-plume-emissions&resampling=nearest&bidx=1&colormap_name=plasma&rescale=1%2C1500&nodata=-9999

And it has in fact a couple of valid data pixels, so GDAL is not making stuff up, it just in addition to these few stray pixels pulls in values from more of the "nearest" pixels, which happen to be far away in the other tile, separate by an area of nodata values.

I think this is a pathological case of stray pixels close enough to the main blob of real data that they get caught by bilinear interpolation.

@vincentsarago may find this interesting. 😄 

We should solve it by using nearest neighbor interpolation on this dataset, as @smohiudd suggested.

@siddharth0248, will you change the config for this dataset to use nearest neighbor for rendering - unless something speaks against that choice?

**Comment by j08lue** [comment]
We could also tell the authors that they should crop their rasters to remove these stray detections which are far away from the plume - I'd think that these are artifacts.

**Comment by j08lue** [comment]
> I don't know if this is useful at all, but in the example given the shadow is caused by the rendering of this tile:

@danielfdsilva, I think your comment above https://github.com/NASA-IMPACT/veda-ui/issues/600#issuecomment-1678780204 is the best lead we have. 

I wonder when this tile gets pulled and why: it gets loaded even when the map is at a much higher zoom level: try to zoom far in (13 or so) and then reload - the app will request the tiles at that zoom level plus this one at level 7 or 8. Y tho?

**Comment by smohiudd** [comment]
I recreated the affected COG yesterday and I think that may have fixed it - I'm not seeing the issue anymore for 05-04 (can someone else confirm?).

Here is the COG info for the old and new files.

**Old COG:**
```bash

COG: True
Compression: ZSTD
ColorSpace: None

Profile
    Width:            71
    Height:           129
    Bands:            1
    Tiled:            True
    Dtype:            float32
    NoData:           -9999.0
    Alpha Band:       False
    Internal Mask:    False
    Interleave:       BAND
    ColorMap:         False
    ColorInterp:      ('gray',)
    Scales:           (1.0,)
    Offsets:          (0.0,)

Geo
    Crs:              EPSG:4326
    Origin:           (-46.450625050282454, -23.630816986890196)
    Resolution:       (0.000542232520256367, -0.000542232520256367)
    BoundingBox:      (-46.450625050282454, -23.700764982003268, -46.41212654134425, -23.630816986890196)
    MinZoom:          11
    MaxZoom:          11

Image Metadata
    AREA_OR_POINT: Area

Image Structure
    COMPRESSION: ZSTD
    INTERLEAVE: BAND
    LAYOUT: COG

Band 1
    ColorInterp: gray

IFD
    Id      Size           BlockSize     Decimation           
    0       71x129         256x256       0
    1       36x65          256x256       2
    2       18x33          256x256       4
    3       9x17           256x256       8
    4       5x9            256x256       14
    5       3x5            256x256       24
    6       2x3            256x256       36
    7       1x2            256x256       71
    8       1x1            256x256       71
```
**New COG**
```bash
COG: True
Compression: DEFLATE
ColorSpace: None

Profile
    Width:            71
    Height:           129
    Bands:            1
    Tiled:            True
    Dtype:            float32
    NoData:           -9999.0
    Alpha Band:       False
    Internal Mask:    False
    Interleave:       BAND
    ColorMap:         False
    ColorInterp:      ('gray',)
    Scales:           (1.0,)
    Offsets:          (0.0,)

Geo
    Crs:              EPSG:4326
    Origin:           (-46.450625050282454, -23.630816986890196)
    Resolution:       (0.000542232520256367, -0.000542232520256367)
    BoundingBox:      (-46.450625050282454, -23.700764982003268, -46.41212654134425, -23.630816986890196)
    MinZoom:          11
    MaxZoom:          11

Image Metadata
    AREA_OR_POINT: Area
    OVR_RESAMPLING_ALG: MODE

Image Structure
    COMPRESSION: DEFLATE
    INTERLEAVE: BAND
    LAYOUT: COG

Band 1
    ColorInterp: gray

IFD
    Id      Size           BlockSize     Decimation           
    0       71x129         512x512       0
```
